### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by syberkitten**
Hi Guys

Wanted to add a few small additions to the project I guess
most of the users might benefit:

1. automatically stdout everything - this comes in handy.
2. -T --title options, to give custom title name to page in case there are no files.
3. added an "epipebomb" safety measure (method inside index.js) which eliminates "EPIPE" exception which mostly happens
when multiple pipes are used and they are not closed. (can read about it)

I'm mostly using frontail to pipe through along with sending to browser
so it allows chaining multiple frontails, in multiple browser windows 
for example (is in mobile testing) :

```
node dist/connect-android.js | frontail - -p 9001 -T All |  node dist/scenario.js connect | frontail - -p 9002 -T Test
```

The above allows opening two browsers while each having a different output from frontail
and different titles.

looking forward to your remarks and ideas :)

### CODE REVIEW

**Comment by philippwaller** [comment]
Great work! I am not sure if I like the "automatically stdout everything" approach. I prefer to activate features via flags. The title option is very handy! I running several docker instances and will appreciate this feature.

**Comment by mthenw** [comment]
@syberkitten thanks for contribution. Can you split those features into different PRs?

**Comment by syberkitten** [comment]
Hey @mthenw, thanks I'll try do it as soon as possible -)

**Comment by syberkitten** [comment]
@mthenw There is an idea i would like to discuss with you,
it's a new feature that is interesting to allow 
message sending to the browser, and extending the 
frontaill javascript code to allow be triggered by certain events.

it should serve the purpose of allowing a trigger on the browser
side while the logs are streaming.

which is good in cases where we want certain log patterns to trigger
certain "alerts" or UI elements on the front.

we have everything ready in this stack, just need to design proper domain
language to do it.

the simplest approach this idea is simply adding the ability to connect to the socket
on the browser and send extra command.

along with it, is to add an option on frontail such as:
```
frontail --js 'extensions.wdiget.js' 
```
This will load up the js which in turn can be either
a kind of controller / proxy that you can communicate with,
from your code (while knowing the port frontail runs at).

All this is neat since it runs while that tail is running
and opens up quite a lot of possibilites.

In my case its actually being more re-active to streaming logs
and allow extensibility to enhance the tail while keeping it as 
simple as it is.
would love to hear what do you think? ) ...

**Pull request closed without merging**
