### PR TITLE
Added configuration to fix #108

### LINKED ISSUE #108: Allow custom path
I'm trying to implement the Frontail with my test environment.

Problem:
I can't expose too many ports to my team test. So I decide add paths inside the port 80 but the Frontail doesn't expected that and don't rewrite the path of JS dependencies.

I added the path "tail-archiver"
image

And errors was raised cause don't found the dependencies:
image

### PR DESCRIPTION
**Pull request by mgoffan**
Added a `--path` parameter to add a prefix to the url to serve the static assets

### CODE REVIEW

**Comment by mgoffan** [comment]
@koss789 Thank you. Forgot to update the README file. Just pushed it.

**Comment by mthenw** [comment]
Hey @mgoffan,

thanks for the PR. The thing is that it doesn't work for me. I'm running following command:

```
./bin/frontail --path /test  /var/log/system.log
```

Then open the browser and see

screenshot 2018-04-06 13 08 23

**Comment by koss789** [comment]
@mthenw With '--path' specified, frontail won't work without proxying the resources and socket connections.
The main problem is with /socket.io/socket.io.js
In your test you are serving socket.io.js at localhost:9001/socket.io/socket.io.js, requesting at localhost:9001/test/socket.io/socket.io.js and get 404 because there is no such file. 
But when you use frontail with nginx, you serve this file at localhost:9001/socket.io/socket.io.js, and when it is requested at localhost:80/test/socket.io/socket.io.js, nginx proxies it to 9001/.. and frontail UI gets it.
It was the main issue to make socket.io.js avaliable at root, but to send socket requests to folder.

**Comment by mthenw** [comment]
@koss789 yeah, thanks for an explanation. I think we need to make both scenarios working before merging. Otherwise, it will be confusing and look like a broken thing.

**Comment by mgoffan** [comment]
@mthenw I just pushed a fix for socket.io. It should be working alright now.

**Comment by mthenw** [comment]
@mgoffan thanks for contribution. I've made few more changes and merged it as https://github.com/mthenw/frontail/pull/120.

**Pull request closed without merging**
