### PR TITLE
chore(docs): fix help option

### LINKED ISSUE #53: README lists -h option as alias for both --help and --host
In the project README under Usage the option `-h` is listed as an alias for both `--help` and `--host`. When I run `frontail -h` it seems to actually refer to `--host`:

```
error: option `-h, --host <host>' argument missing
```

Also, running `frontail --help` lists the same thing:

```
Usage: frontail [options] [file ...]

Options:

-h, --help                    output usage information
...
-h, --host <host>             listening host, default 0.0.0.0
...
```

Anyway, not a huge deal, but I just thought I'd mention it.

### PR DESCRIPTION
**Pull request by mojoaxel**
This should fix #53 after [commander.js@3.0.0](https://github.com/tj/commander.js/issues/1001) is released.

see [3.0.0/CHANGELOG](https://github.com/tj/commander.js/blob/release/3.0.0/CHANGELOG.md#300-0-prerelease--2019-07-28)

### CODE REVIEW

**Comment by mthenw** [comment]
Great stuff. I will review and test it later.

**Comment by mthenw** [comment]
I tested it and looks good.

**Comment by mojoaxel** [comment]
:worried: commander.js has not yet been released, yet. This pull-request draft relies on a prerelease at the moment. **It should not be released as it is at the moment.**

After v3.0.0 has been released we should change the dependency and than we frontail should be released.

**Comment by mthenw** [comment]
Yeah, I got it but I tested it and works fine. Have you spot any errors?

**Comment by mojoaxel** [comment]
> Yeah, I got it but I tested it and works fine. Have you spotted any errors?

I'm just not sure if this 3.0.0-0 pre-release is reliable. I don't have a good feeling about this. But it works :+1:

**Comment by mthenw** [comment]
OK, let's wait a few days. Maybe the release will happen in the meantime.

**Comment by mojoaxel** [comment]
https://github.com/tj/commander.js/releases/tag/v3.0.0
@mthenw You can now update the dependency and release this :rocket:

**Comment by mthenw** [comment]
It's not published to npm yet.

**Pull request merged**
